export const configs = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  PRODUCTS_BASE_URL: process.env.NEXT_PUBLIC_PRODUCTS_BASE_URL,
  CONSUMER_KEY: process.env.NEXT_PUBLIC_CONSUMER_KEY,
  CONSUMER_SECRET: process.env.NEXT_PUBLIC_CONSUMER_SECRET,
};
